spring:
  application:
    name: HMS
  datasource:
    url: jdbc:mysql://localhost:3306/hms?createDatabaseIfNotExist=true
    username: root
    password: joshua6775
  flyway:
    enabled: false
    baseline-on-migrate: false
    locations: classpath:db/migration

admin:
  username: admin
  password: 1234